name: File Service CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "services/file/**"
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manually triggering the CI"
        required: true
        default: "Manual test"

jobs:
  file-service-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/file

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.11"
          cache-dependency-path: "**/go.sum"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: services/file
          args: --timeout=5m ./...

      - name: Run Tests with Coverage
        run: go test -v -coverprofile=test/coverage.out ./internal/...

      - name: Convert coverage to HTML report
        run: go tool cover -html=test/coverage.out -o coverage.html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: services/file/coverage.html
          retention-days: 7
