name: Shared Library CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "pkg/shared/**"
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manually triggering the CI"
        required: true
        default: "Manual test"

jobs:
  shared-library-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkg/shared
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.11"
          cache-dependency-path: "**/go.sum"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: services/hangout
          args: --timeout=5m ./...
